config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings, only: [:destroy, :update, :edit]
  resources :airplanes do
    resources :bookings, only: [:create]
  end
  get "dashboard", to: "pages#dashboard"
    root to: 'pages#home'
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_model_and_category,
    against: [ :model, :category ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :airplane
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :airplanes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :airplanes, dependent: :destroy
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def index
    if params[:query].present?
      @airplanes = policy_scope(Airplane.search_by_model_and_category(params[:query]).geocoded)
    else
      @airplanes = policy_scope(Airplane.all.geocoded)
    end

    @markers = @airplanes.map do |airplane|
      {
        lat: airplane.latitude,
        lng: airplane.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { airplane: airplane }),
        image_url: helpers.asset_url("private_jet_icon.png"),
      }
    end
  end

  def show
    @airplane = Airplane.geocoded.find(params[:id])
    @booking = Booking.new
    @markers = 
    [{
      lat: @airplane.latitude,
      lng: @airplane.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { airplane: @airplane }),
      image_url: helpers.asset_url("private_jet_icon.png"),
    }]
    authorize @airplane
  end

  def new
    @airplane = Airplane.new
    authorize @airplane
  end

  def create
    @user = current_user
    @airplane = Airplane.new(airplane_params)
    @airplane.user = @user
    if @airplane.save
      redirect_to airplane_path(@airplane)
    else
      render "new"
    end
    authorize @airplane
  end

  def destroy
    @airplane = Airplane.find(params[:id])
    authorize @airplane
    @airplane.destroy
    redirect_to dashboard_path
  end

  def edit
    @airplane = Airplane.find(params[:id])
    authorize @airplane
  end

  def update
    @airplane = Airplane.find(params[:id])
    authorize @airplane
    @airplane.update(airplane_params)
    redirect_to dashboard_path
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  private

  def airplane_params
    params.require(:airplane).permit(:address, :model, :category, :seat_capacity, :range, :daily_price, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, :set_airplane
    include Pundit

    # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    # Uncomment when you *really understand* Pundit!
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(root_path)
    end

    
    
    private
    
    def set_airplane
      @airplane = Airplane.new
      
    end

    def skip_pundit?
        devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @booking = Booking.new(booking_params) # je crée une nouvelle variable + je lui donne les données de mon formulaire
    @airplane = Airplane.find(params[:airplane_id]) # je recupère l'id de airplane dans les params de ma page
    @booking.airplane_id = @airplane.id # je donne la donnée  recupérée en ligne 4
    @booking.user_id = current_user.id #je recupère la dernière donnée pour créer mon instance booking
    #@booking.save #maintenant qu ej'ai toutre sles odnnées j'enregsire
    #redirect_to airplane_path(@airplane)
    if @booking.save
       redirect_to dashboard_path, notice: 'Thank You For booking!'
      #format.json  { render json: Email.create(email_params) }
    else
       redirect_to airplane_path(@airplane), notice: 'Start again!'
    end
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to dashboard_path
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airplanes/_info_window.html.erb
<h2><%= airplane.model %></h2>
<p><%= airplane.category %></p>
<p><%= airplane.address %></p>

app/views/airplanes/edit.html.erb
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1 style="text-align: center;">Add your plane</h1>
        <% if policy(Airplane).create? %>
          <%= simple_form_for @airplane do |f| %>
            <%= f.input :model, collection: ["Cessna Denali", "Cessna Caravan", "Cirrus SR20", "Cirrus SR22", "Dassault Falcon", "Gulfstream G700"] %>
            <%= f.input :category, collection: ["Regional jet", "Light jet", "Medium jet", "Long haul jet" ] %>
            <%= f.input :seat_capacity %>
            <%= f.input :range %>
            <%= f.input :address %>
            <%= f.input :daily_price %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.button :submit, class: 'btn btn-primary' %>
          <% end %>
        <% else %>
          <h2>You cannot add a plane, you need permissions !</h2>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/airplanes/index.html.erb
<div class="container" style="display: grid; justify-content: center;">
  <%= form_tag airplanes_path, method: :get, class: 'd-flex mt-4' do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control mr-2",
    placeholder: "Find your jet here" %>
    <%= submit_tag "Search", class: "btn-search" %>
  <% end %> 
</div>
<br>
<h1 style="text-align: center; font-weight: bold;" >🛫 Our private jets around the world 🛬</h1>
<br>
<div class="container-2">
  <div class="card-box">
    <% @airplanes.each do |airplane| %>
    <div class="card-trip">
      <%= link_to airplane_path(airplane) do %>
        <% if airplane.photos.first %>
          <%= cl_image_tag airplane.photos.first.key, crop: :fill, id: 'photo' %>
        <% end %>    
        <div class="card-trip-infos">
          <div>
            <h2><%= airplane.model %></h2>
            <p><%= airplane.address %></p>
          </div>
          <h2 class="card-trip-pricing" style="margin-bottom: 7px;"><%= airplane.daily_price %> €</h2>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
    <div id="map" style="width: 100%; height: 600px; margin-bottom: 10px; margin-top: 10px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/airplanes/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://www.pro-sky.com/files/de/content/1.png)">
<h1 id="add"> <i class="fas fa-globe-europe"></i><strong> ADD YOUR PLANE ! </strong></h1>
</div>


<br>

  <div class="container ">
    <div class="row justify-content-center">
      <div class="col-md-8 avion">
      <!--   <h1 style="text-align: center;">Add your plane</h1> -->
        <% if policy(Airplane).create? %>
          <%= simple_form_for @airplane do |f| %>
            <%= f.input :model, collection: ["Cessna Denali", "Cessna Caravan", "Cirrus SR20", "Cirrus SR22", "Dassault Falcon", "Gulfstream G700"]%>
            <%= f.input :category, collection: ["Regional jet", "Light jet", "Medium jet", "Long haul jet" ] %>
            <%= f.input :seat_capacity %>
            <%= f.input :range %>
            <%= f.input :address %>
            <%= f.input :daily_price %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.button :submit, class: 'btn btn-secondary btn-lg btn-block' %>
          <% end %>
            <i class="fas fa-plane fa-2x avion_image"></i>
        <% else %>
          <h2>You cannot add a plane, you need permissions !</h2>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/airplanes/show.html.erb
<div class="container container-show">
  <div id="titre"><h1><strong><%= @airplane.model %></strong></h1></div>
  <div class= "one ">
    <% @airplane.photos.each do |photo| %>
      <div class="grid-adjuster"><%= cl_image_tag photo.key, crop: :fill, class: "imageshow" %></div>
    <% end %>
  </div>
  <hr style="border-top: 1px solid #6C757D;">
  <div class="description-booking">
    <div class="airplane-infos ml-10">
      <p><i class="fas fa-plane"></i><strong> Category :</strong> <%= @airplane.category %></p>
      <p><i class="fas fa-exchange-alt"></i><strong> Range :</strong> <%= @airplane.range%> km </p>
      <p><i class="fas fa-chair"></i><strong> Capacity : </strong><%= @airplane.seat_capacity %> people</p>
      <p><i class="fas fa-location-arrow"></i><strong> Location : </strong><%= @airplane.address %></p>
      <p id="price"><i class="fab fa-angellist"></i><strong> <%= @airplane.daily_price%> euros/day</p></strong>
   </div>
   <div class="booking-form">
  <%= simple_form_for [@airplane, @booking] do |f| %>
    <div class="start_date"><%= f.input :start_date, as: :string, required: false, input_html: { id: "start_date" } %></div>
    <%= f.input :end_date, as: :string, required: false, input_html: { id: "end_date" } %>
    <%= f.button :submit, class: 'btn btn-dark', id: 'button-booking', disabled:true %>
  <% end %>
    </div>
  </div>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/bookings/edit.html.erb
<div class="booking-form row ml-5">
  <%= simple_form_for [@booking] do |f| %>
    <strong> <%= f.input :start_date %> </strong>
    <strong>  <%= f.input :end_date %> </strong>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Click & fly </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <br>
  <h1 style="text-align: center; font-weight: bold;">Hello, <%=@user.email%> 😊</h1> 
  <br>
  <h2 style="font-weight: bold; margin-left: 10px;">My bookings</h2>
  <div class="cards-dashboard">
    <% @user.bookings.each do |booking| %>
      <div class="card-product">
      <% if booking.airplane.photos.first %>
        <%= cl_image_tag booking.airplane.photos.first.key, crop: :fill %>
      <% end %>
        <div class="card-product-infos">
          <h2><%= booking.airplane.model %></h2>
          <p>From <%= booking.start_date %> to <%= booking.end_date %>
          <br>
          Total price: <%= number_with_precision(booking.airplane.daily_price * (booking.end_date - booking.start_date).to_f, precision: 0, delimiter:' ') %>€ (<span><%= number_with_precision((booking.end_date - booking.start_date).to_f, precision: 0) %> days</span>)</p>
          <%= link_to edit_booking_path(booking) do %>
            <p><i class="fas fa-pencil-alt"></i> Modify your booking
          <% end  %>
          <br>
          <%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you really sure ?"} do %>
            <i class="fas fa-trash"></i> Delete your booking</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <hr style="border-top: 10px solid rgba(0, 0, 0, 0.1);">
  <h2 style="font-weight: bold; margin-left: 10px;">My planes</h2>
  <div class="cards-dashboard" style="margin-bottom: 10px;">
    <% @user.airplanes.each do |airplane| %>
      <div class="card-product">
        <% if airplane.photos.first %>
          <%= cl_image_tag airplane.photos.first.key, crop: :fill %>
        <% end %>
        <div class="card-product-infos">
          <h2 style="margin-bottom: 20px;"><%= airplane.model %></h2>            
            <p><%= link_to edit_airplane_path(airplane) do %>
                <i class="fas fa-pencil-alt"></i> Modify your plane
            <% end %>
            <br>
            <%= link_to airplane_path(airplane), method: :delete, data: { confirm: "Are you sure ?"} do %>
              <i class="fas fa-trash"></i> Remove your plane</p>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div style="text-align: center; margin-bottom: 10px;">
    <a href="https://clickandfly-francoisng.herokuapp.com/airplanes/new"><button class="btn-search-2">Add a plane</button></a>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-background" style="background-image: url('<%= image_path "private-jet-inside.jpeg"%>')">
  <div class="container h-100">
  <div class="content">
    <h2 class="tag-line white"><strong>Find your Private Jet</strong></h2> 
    <div class="d-flex h-10">
      <form>
        <div class="form-row">
          <div class="col-3 form-group">
            <label class="lab linebrown">Location</label>
            <input type="text" class="form-control" placeholder="Where are you?">
          </div>
          <div class="col-3 form-group">
            <label class="lab linebrown">Start date</label>
            <input type="date" class="form-control" placeholder="Add dates">
          </div>
          <div class="col-3 form-group">
            <label class="lab linebrown">End date</label>
            <input type="date" class="form-control" placeholder="Add dates">
          </div>
          <div class="col-3 form-group">
            <label class="lab linebrown">Category</label>
            <input type="text" class="form-control" placeholder="Add category">
          </div>
        </div>
      </form>
    </div>
  </div>
  </div>
</div>
<div class="row p-5 d-flex justify-content-around">
  <div class="col-4">
    <h4 class="text-center linewhite">Compare the options and choose the one which best suits you</h4>
    <p class="pt-3">
      Hiring a private flight with us is very easy: choose from where you want to fly, the number of passengers and the type of private jet you want to rent (Light Jet, Medium Jet and Large Jet)</p>
  </div>
  <div class="col-4">
    <h4 class="text-center linewhite">There is no corner in the sky in which we cannot make you fly</h4>
    <p class="pt-3">
    Our service reaches more than 5000 airports in the world. We will take you wherever you want both commercial and private airport.
    </p>
  </div>
  <div class="col-4">
    <h4 class="text-center linewhite">Flying distances in the safest and most comfortable private jet</h4>
    <p class="pt-3">
    We have selected only the best of general aviation: pilots chosen on an expertise basis and latest aircraft, to fly with the greatest safety and 
    </p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/francoisng/clickandfly" target="_blank"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the Click & Fly team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "click&fly_nav_logo_2.png" %>
    <% end %>
    <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
          <%= link_to "Jets", airplanes_path, class: "nav-link" %>
        </li>
        </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">

          <%#= link_to "Offers", "#", class: "nav-link" %>
        </li>
          <%#= link_to "Messages", "#", class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/slegrez", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", dashboard_path, class: "dropdown-item" %>
            <%= link_to "My Planes", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>